<?xml version="1.0" encoding="utf-8"?><Database Name="MyDbContext" Class="DrivingLicenseDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=MyDbContext;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MyDbContextConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DrivingLicenseData" Member="DrivingLicenseDatas">
    <Type Name="DrivingLicenseData">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnswerOne" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AnswerTwo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AnswerThree" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AnswerFour" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CorrectAnswer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswersPoints" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImageSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImageNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SteppeNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Definition" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>